apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: couttshasherpes-com-tls
spec:
  secretName: couttshasherpes-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: couttshasherpes.com
  dnsNames:
    - couttshasherpes.com
    - www.couttshasherpes.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - couttshasherpes.com
          - www.couttshasherpes.com
          
